ARG BASE_IMAGE="quay.io/jupyter/scipy-notebook:2025-11-10"

FROM ${BASE_IMAGE}

# Args are scoped and removed after FROM
ARG BASE_IMAGE
ARG BUILD_DATE="unknown"
ARG VCS_REF="unknown"

LABEL org.opencontainers.image.title="Numina pipelines in jupyter lab" \
      org.opencontainers.image.authors="Sergio Pascual <sergiopr@fis.ucm.es>" \
      org.opencontainers.image.source="https://github.com/guaix-ucm/docker-stacks" \
      org.opencontainers.image.description="Jupyter lab stack with GTC pipelines based in numina" \
      org.opencontainers.image.vendor="GUAIX - Universidad Complutense de Madrid" \
      org.opencontainers.image.url="https://guaix.ucm.es" \
      org.opencontainers.image.base.name=${BASE_IMAGE} \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.revision=${VCS_REF}

# Possible future labels
# org.opencontainers.image.version="1.0.0" 
# org.opencontainers.image.documentation="https://github.com/guaix-ucm/docker-stacks/wiki"
#  org.opencontainers.image.licenses="" \


COPY --chown=${NB_UID}:${NB_GID} requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
